### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined

### ISSUE THREAD

**Issue by iCodeForBananas** [postcasio/slash-closer#1]
```
Uncaught TypeError: Cannot read property 'getBufferPosition' of undefined
c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\history.js:124
Hide Stack Trace
TypeError: Cannot read property 'getBufferPosition' of undefined
  at TextEditor.module.exports.TextEditor.getCursorBufferPosition (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:1304:34)
  at c:\Users\Michael J. Calkins\.atom\packages\slash-closer\lib\slash-closer.coffee:49:22
  at Emitter.module.exports.Emitter.emit (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:590:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:503:12)
  at Selection.module.exports.Selection.insertText (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\selection.js:446:43)
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:742:31
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:781:27
  at History.module.exports.History.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:1150:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:774:19)
  at TextEditor.module.exports.TextEditor.insertText (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:739:21)
  at TextEditor.object.(anonymous function) [as insertText] (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
  at c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor-component.js:653:23
  at History.module.exports.History.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor.js:1150:26)
  at [object Object].module.exports.React.createClass.onTextInput (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\src\text-editor-component.js:652:30)
  at HTMLDivElement.boundMethod (c:\Users\Michael J. Calkins\AppData\Local\atom\app-0.166.0\resources\app\node_modules\react-atom-fork\lib\ReactCompositeComponent.js:1295:21)
```

I don't know how I started this but in my current window every time I write `<` and then `/` atom freezes and won't write anything.

I restarted atom and then it started working again.

**Comment by iCodeForBananas** [comment]
![screenshot_010615_041609_pm](https://cloud.githubusercontent.com/assets/8272012/5638675/52fc7974-95bf-11e4-80b0-19c9e201c94c.jpg)

**Comment by iCodeForBananas** [comment]
![main nav example](https://cloud.githubusercontent.com/assets/8272012/5638690/960a9c78-95bf-11e4-9812-5626e263cee7.gif)

**Comment by Bashfulmonk** [comment]
Also having the exact same issue. Started to become more frequent. Have had to disable the package for now.
